# 15rules_fedavg.yaml
defaults: []
seed: 42
algorithm: FedAvg
num_clients: 5
num_rules: 15        # <- unchanged legacy model
training:
  batch_size: 32
  client_lr: 1.8e-3
federated:
  rounds: 100
dataset:
  path: "C:\\Graduation Project\\dataset\\preprocessed_data_enriched.pkl"
