# 15rules_prox.yaml
defaults: []
seed: 42
algorithm: FedAvg
num_clients: 5
num_rules: 15
training:
  batch_size: 32
  client_lr: 1.8e-3
federated:
  rounds: 100
dataset:
  path: "PATH_TO_FILE\\preprocessed_data_enriched.pkl"
