# 15rules_scaffold.yaml
seed: 42
defaults: [sweepwin_fedavg]
algorithm: SCAFFOLD
server_lr: 0.02
training:
  batch_size: 32
  client_lr: 0.02
num_clients: 5
num_rules: 15
federated:
  rounds: 100
dataset:
  path: "PATH_TO_FILE\\preprocessed_data_enriched.pkl"
