# interpretable/configs.yaml
train_parquet: "PATH_TO_FILE/tabular_train.parquet"
test_parquet:  "PATH_TO_FILE/tabular_test.parquet"
subsample:      100000
seed:           42

corels_grid:
  C:          [0.01, 0.1, 1.0]
  max_depth:  [2, 3]

frl_grid:
  n_chains:   [4, 8]
  max_depth:  [2, 3]
